djcrm/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path,include
from leads.views import LandingPage
from django.contrib.auth.views import LoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , LandingPage.as_view()),
    path('leads/' , include('leads.urls' , namespace='leads')) , 
    path('login/'  , LoginView.as_view())
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL , document_root = settings.STATIC_ROOT)

leads/urls.py
from django.urls import path
from .views import (
     LeadListView,
     LeadCreateView,
     LeadDeleteView,
     LeadUpdateView,
     LeadDetailView)


app_name = 'leads'

urlpatterns = [
    path('' , LeadListView.as_view() , name='lead-list'),
    path('update/<int:pk>/' , LeadUpdateView.as_view() , name='lead-update'),
    path('delete/<int:pk>/' , LeadDeleteView.as_view() , name='lead-delete'),
    path('<int:pk>/' , LeadDetailView.as_view() , name='lead-detail'),
    path('create/' , LeadCreateView.as_view() , name='lead-create')
]

leads/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.



class User(AbstractUser):
    pass



class Lead(models.Model):


    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    age = models.IntegerField(default=0)
    agent = models.ForeignKey("Agent" , on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

class Agent(models.Model):

    user = models.OneToOneField(User , on_delete=models.CASCADE)

    def __str__(self):
        return self.user.email

leads/forms.py
from django import forms
from .models import Lead


class LeadModelForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = (
            'first_name',
            'last_name',
            'age',
            'agent',
        )
        
class LeadForm(forms.Form):
    first_name = forms.CharField()
    last_name = forms.CharField()
    age = forms.IntegerField(min_value=0)

leads/views.py
from django.core.mail import send_mail
from django.http.response import HttpResponse
from django.shortcuts import render ,redirect , reverse
from django.http import HttpResponse
from .models import Lead , Agent
from .forms import LeadForm ,LeadModelForm
from django.views import generic

# Create your views here.
class LandingPage(generic.TemplateView):
    template_name = 'leads/landing.html'

class LeadListView(generic.ListView):
    queryset = Lead.objects.all()
    template_name = 'leads/lead_list.html'
    context_object_name = 'leads'

class LeadDetailView(generic.DetailView):
    queryset = Lead.objects.all()
    template_name = 'leads/lead_detail.html'
    context_object_name = 'lead'

class LeadUpdateView(generic.UpdateView):
    template_name = 'leads/lead_update.html'
    form_class = LeadModelForm
    queryset = Lead.objects.all()

    def get_success_url(self):
        return reverse('leads:lead-list')

class LeadDeleteView(generic.DeleteView):
    template_name = 'leads/lead_delete.html'
    queryset = Lead.objects.all()

    def get_success_url(self):
        return reverse('leads:lead-list')


class LeadCreateView(generic.CreateView):
    template_name = 'leads/lead_create.html'
    form_class = LeadModelForm

    def get_success_url(self) :
        return reverse('leads:lead-list')

    def form_valid(self, form):
        send_mail(
            subject='A new lead has been created',
            message='Please go to the Lead Application to check it',
            from_email='test@test.com',
            recipient_list=['test2@test.com']
        )
        return super(LeadCreateView,self).form_valid(form)

def landing_page(request):
    return render(request , 'landing.html')

def lead_list(request):
    leads  = Lead.objects.all()
    context = {
        "leads" : leads
    }
    return render(request,'leads/lead_list.html' , context)

def lead_detail(request , pk):
    lead = Lead.objects.get(id=pk)
    context = {
        "lead" : lead
    }
    return render(request , 'leads/lead_detail.html' , context)



def lead_update(request , pk):
    lead = Lead.objects.get(id=pk)
    form = LeadModelForm(instance=lead)
    if request.method == 'POST':
        form = LeadModelForm(request.POST,instance=lead)
        if form.is_valid():
            form  = LeadModelForm(request.POST , instance=lead)
            form.save()
            return redirect('/leads')
    context = {
        'form' : form,
        'lead' : lead
    }
    return render(request , 'leads/lead_update.html' , context)



def lead_create(request):
    form = LeadModelForm()
    if request.method=='POST':
        print("This is a post request")
        form = LeadModelForm(request.POST)
        if form.is_valid():
            '''print(form.cleaned_data)
            agent = form.cleaned_data['agent']
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            age = form.cleaned_data['age']
            Lead.objects.create(
                first_name = first_name,
                last_name = last_name,
                age = age,
                agent = agent
            )
            print("The Lead is created successfully")'''
            form.save()
            return redirect('/leads')

    context={
        "form" : form
    }
    return render(request,'leads/lead_create.html' , context)


#def lead_create_submit(request):
    #return render(request , 'leads/lead_create_submit.html')


def lead_delete(request , pk):
    lead  = Lead.objects.get(id=pk)
    lead.delete()
    return redirect('/leads')

leads/templates/leads/lead_create.html
{% extends 'base.html' %}
{% block content %}
    <a href="{% url 'leads:lead-list' %}">Go back to Leads</a>
    <hr/>
    <h1> Create a Lead </h1>
    <form action='.' method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
{% endblock content %}

leads/templates/leads/lead_create_submit.html
{% extends 'base.html' %}
{% block content %}
<a href="/leads/">Go back to Leads</a>
    <hr/>
    <h1> The Lead has been creates successfully </h1>
{% endblock content %}

leads/templates/leads/lead_delete.html
{% extends 'base.html' %}
{% block content %}
    <a href="{% url 'leads:lead-list' %}">Go back to Leads</a>
    <hr/>
    <h1> Are you sure you want to delete the Lead ? </h1>
    <form action='.' method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
{% endblock content %}

leads/templates/leads/lead_detail.html
{% extends 'base.html' %}
{% block content %}
    <a href="/leads/">Go back to Leads</a>    <a href="{% url 'leads:lead-update' lead.pk %}">Update this lead</a>       <a href="{% url 'leads:lead-delete' lead.pk %}">Delete this lead</a>
    <hr/>
    <h1> These are the details of {{lead.first_name}} </h1>
    <p> {{lead.first_name}}'s age is {{lead.age}}</p>
    <p> The agent responsible for this lead is {{lead.agent}}</p>
{% endblock content %}

leads/templates/leads/lead_list.html
{% extends 'base.html' %}
{% block content %}
    <a href="{% url 'leads:lead-create' %}">Create a Lead</a>
    <hr />
    <h1> These are the list of our leads </h1>
    {% for lead in leads %}
    <div class="lead">
        <a href="{% url 'leads:lead-detail'  lead.pk %}">{{lead.first_name}} {{lead.last_name}}</a>. Age is {{lead.age}}
    </div>
    {% endfor %}
{% endblock content %}

leads/templates/leads/lead_update.html
{% extends 'base.html' %}
{% block content %}
    <a href="{%  url 'leads:lead-detail' lead.pk %}">Go back to {{lead.first_name}} {{lead.last_name}}</a>
    <hr/>
    <h1> Update the Lead {{lead.first_name}} {{lead.last_name}}</h1>
    <form action="." method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DJCRM</title>
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
</head>
<body>

    <div class="max-w-7xl mx-auto">
        {% include 'navbar.html' %}
        {% block content %}
        {% endblock content %}
    </div>

    {% include 'scripts.html' %}

</body>
</html>

templates/landing.html
{% extends 'base.html' %}

{% block content %}


  
{% endblock content %}


<section class="text-gray-600 body-font">
    <div class="container px-5 py-24 mx-auto">
      <div class="flex flex-col text-center w-full mb-20">
        <h2 class="text-xs text-indigo-500 tracking-widest font-medium title-font mb-1">ROOF PARTY POLAROID</h2>
        <h1 class="sm:text-3xl text-2xl font-medium title-font mb-4 text-gray-900">Master Cleanse Reliac Heirloom</h1>
        <p class="lg:w-2/3 mx-auto leading-relaxed text-base">Whatever cardigan tote bag tumblr hexagon brooklyn asymmetrical gentrify, subway tile poke farm-to-table. Franzen you probably haven't heard of them man bun deep jianbing selfies heirloom prism food truck ugh squid celiac humblebrag.</p>
      </div>
      <div class="flex flex-wrap">
        <div class="xl:w-1/4 lg:w-1/2 md:w-full px-8 py-6 border-l-2 border-gray-200 border-opacity-60">
          <h2 class="text-lg sm:text-xl text-gray-900 font-medium title-font mb-2">Shooting Stars</h2>
          <p class="leading-relaxed text-base mb-4">Fingerstache flexitarian street art 8-bit waistcoat. Distillery hexagon disrupt edison bulbche.</p>
          <a class="text-indigo-500 inline-flex items-center">Learn More
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
              <path d="M5 12h14M12 5l7 7-7 7"></path>
            </svg>
          </a>
        </div>
        <div class="xl:w-1/4 lg:w-1/2 md:w-full px-8 py-6 border-l-2 border-gray-200 border-opacity-60">
          <h2 class="text-lg sm:text-xl text-gray-900 font-medium title-font mb-2">The Catalyzer</h2>
          <p class="leading-relaxed text-base mb-4">Fingerstache flexitarian street art 8-bit waistcoat. Distillery hexagon disrupt edison bulbche.</p>
          <a class="text-indigo-500 inline-flex items-center">Learn More
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
              <path d="M5 12h14M12 5l7 7-7 7"></path>
            </svg>
          </a>
        </div>
        <div class="xl:w-1/4 lg:w-1/2 md:w-full px-8 py-6 border-l-2 border-gray-200 border-opacity-60">
          <h2 class="text-lg sm:text-xl text-gray-900 font-medium title-font mb-2">Neptune</h2>
          <p class="leading-relaxed text-base mb-4">Fingerstache flexitarian street art 8-bit waistcoat. Distillery hexagon disrupt edison bulbche.</p>
          <a class="text-indigo-500 inline-flex items-center">Learn More
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
              <path d="M5 12h14M12 5l7 7-7 7"></path>
            </svg>
          </a>
        </div>
        <div class="xl:w-1/4 lg:w-1/2 md:w-full px-8 py-6 border-l-2 border-gray-200 border-opacity-60">
          <h2 class="text-lg sm:text-xl text-gray-900 font-medium title-font mb-2">Melanchole</h2>
          <p class="leading-relaxed text-base mb-4">Fingerstache flexitarian street art 8-bit waistcoat. Distillery hexagon disrupt edison bulbche.</p>
          <a class="text-indigo-500 inline-flex items-center">Learn More
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
              <path d="M5 12h14M12 5l7 7-7 7"></path>
            </svg>
          </a>
        </div>
      </div>
      <button class="flex mx-auto mt-16 text-white bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg">Button</button>
    </div>
  </section>

templates/scripts.html
<script>
    console.log("Hello World")
</script>

templates/second_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=<device-width>, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Hello World</h1>
    <h1> This is my second page </h1>
    <ul>
        {% for lead in leads %}
        <li>{{lead}}</li>
        {% endfor %}
    </ul>
</body>
</html>